name: tap
description: "Talabalar Amaliyot Platformasi"
version: 1.0.1+3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Commons
  animated_bottom_navigation_bar: ^1.3.3
  tutorial_coach_mark: ^1.2.9
  animated_snack_bar: ^0.4.0
  overlay_support: ^2.1.0
  iconsax_flutter: ^1.0.0
  google_fonts: ^6.3.1
  fl_chart: ^1.1.0
  lottie: ^2.7.0
  intl: ^0.20.2
  table_calendar: ^3.2.0
  buttons_tabbar: ^1.3.15
  page_transition: ^2.2.1

  # Network
  http: ^1.3.0
  http_interceptor: ^2.0.0
  logger: ^2.4.0

  # GPS
  geolocator: ^10.1.0
  google_maps_flutter: ^2.10.0
  url_launcher: ^6.1.14

  # GetX
  get: ^4.7.2
  get_storage: ^2.1.1
  path_provider: ^2.1.4

  # Kesh
  shared_preferences: ^2.3.2

  # NoSql
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

  # Firebase
#  firebase_storage: ^13.0.6
#  firebase_core: ^2.32.0
#  firebase_auth: ^4.20.0
#  cloud_firestore: ^4.17.5
#  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/npuu-icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
      - assets/images/
      - assets/lotties/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf